# Generated by Django 5.0.6 on 2024-07-17 02:02

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_users_table_useractivetokens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserActiveTokens',
            new_name='UserActivateTokens',
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
