# Generated by Django 5.0.6 on 2024-08-07 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('zip_code', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('distance', models.CharField(max_length=30, null=True)),
                ('floor', models.CharField(max_length=10, null=True)),
                ('house_kind', models.CharField(max_length=20, null=True)),
                ('constraction', models.IntegerField(null=True)),
                ('floor_number', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'housing',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('picture', models.FileField(upload_to='picture/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.housings')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
