# Generated by Django 5.0.6 on 2024-08-08 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('picture', models.FileField(upload_to='housing_pictures/')),
                ('order', models.IntegerField()),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.housings')),
            ],
            options={
                'db_table': 'housing_pictures',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
