# Generated by Django 5.0.6 on 2024-08-08 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_housingpictures_delete_pictures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingpictures',
            options={},
        ),
        migrations.RemoveField(
            model_name='housingpictures',
            name='order',
        ),
    ]
