# Generated by Django 5.0.6 on 2024-08-08 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_housingpictures_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housings',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.housingpictures'),
        ),
    ]
