# Generated by Django 5.0.6 on 2024-08-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_housings_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingpictures',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='housingpictures',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
