# Generated by Django 5.0.6 on 2024-07-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_remove_housing_picture_housecomments_housingpictures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingpictures',
            options={},
        ),
        migrations.RemoveField(
            model_name='housingpictures',
            name='price',
        ),
    ]
