# Generated by Django 5.0.6 on 2024-07-17 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_housing_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=15, null=True)),
                ('price', models.IntegerField()),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.housingpictures')),
            ],
            options={
                'db_table': 'detail_house',
            },
        ),
    ]
