# Generated by Django 5.0.6 on 2024-07-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_detailhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='housecomments',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
