# Generated by Django 5.0.6 on 2024-07-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_housecomments_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housecomments',
            name='created_at',
        ),
    ]
