# Generated by Django 5.0.6 on 2024-08-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_users_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
