# Generated by Django 5.0.6 on 2024-08-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_comments_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='update_at',
        ),
        migrations.AddField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='投稿日時'),
        ),
    ]
